# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 10
  - name: Courses
    weight: 20
    identifier: courses
  - name: 0-1 Linux Fundamental 
    PageRef: course/linux/_index.md
    weight: 10
    parent: courses
  - name: 0-2 Git 
    PageRef: course/git/_index.md
    weight: 20
    parent: courses
  - name: 1-1 Golang
    PageRef: course/go/_index.md
    weight: 21
    parent: courses
  - name: 1-2 Rust
    PageRef: course/rust/_index.md
    weight: 22
    parent: courses
  - name: 3-1 tinySQL
    PageRef: course/tinySQL/_index.md
    weight: 30
    parent: courses
  - name: 3-2 tinyKV
    PageRef: course/tinykv/_index.md
    weight: 31
    parent: courses
  - name: Blog
    PageRef: post/_index.md
    weight: 30
  - name: Contact
    PageRef: contact/index.md
    weight: 60
  - name: My Pages
    url: /#my_section
    weight: 70
  - name: About
    PageRef: about/index.md
    weight: 80
